const order=Object.keys(S);let current='start';let sid='';const ambient=document.getElementById('ambient');ambient.volume=.16;
function uuid(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function eventName(screen,label){const map={start:'session_started',control:'reached_control',safetyStop:'safety_exit',final:'completed'};if(screen==='clarity'){if(label==='Да')return'clarity_yes';if(label==='Частично')return'clarity_partial';if(label==='Нет')return'clarity_no'}return map[screen]||('screen_'+screen)}
function track(name){if(!name)return;try{let a=JSON.parse(localStorage.getItem('anon_events')||'[]');a.push({event:name,ts:new Date().toISOString(),sid,version:'3.0'});localStorage.setItem('anon_events',JSON.stringify(a.slice(-500)))}catch(e){};const c=window.APP_CONFIG&&APP_CONFIG.goatcounterCode;if(c){const u='https://'+c+'.goatcounter.com/count?p='+encodeURIComponent('/event/'+name)+'&t='+encodeURIComponent(name)+'&e=1';fetch(u,{mode:'no-cors',keepalive:true}).catch(()=>{})}}
function accept(){localStorage.setItem('consent_v','3.0');localStorage.setItem('consent_at',new Date().toISOString());go('start')}
function go(id,label=''){if(id==='worksheet'){window.open('worksheet-v3.pdf','_blank');track('worksheet_opened');return}if(id==='finishSafety'){fadeOut();track('safety_session_ended');current='start';render();return}if(id==='finish'){fadeOut();track('session_completed');current='start';render();return}if(id==='start'){sid=uuid()}current=id;if(id==='start')track('session_started');if(id==='safetyStop')track('safety_exit');if(id==='control')track('reached_control');render();scrollTo(0,0)}
function choose(label,id){if(current==='clarity'){track(label==='Да'?'clarity_yes':label==='Частично'?'clarity_partial':'clarity_no')}go(id,label)}
function render(){const s=S[current];document.getElementById('app').innerHTML=`<h1>${s[0]}</h1>${s[1]}<div class="buttons">${s[2].map(b=>`<button class="${b[2]||''}" onclick="${b[1]==='accept'?'accept()':`choose('${b[0].replaceAll("'","\\'")}','${b[1]}')`}">${b[0]}</button>`).join('')}</div>`;const idx=Math.max(0,order.indexOf(current));document.getElementById('bar').style.width=Math.min(100,Math.round(idx/order.length*100))+'%';document.getElementById('restart').style.visibility=current==='consent'?'hidden':'visible'}
function toggleAudio(){if(ambient.paused){ambient.play().then(()=>{document.getElementById('audioBtn').textContent='♪ Фон: вкл.'}).catch(()=>{})}else{fadeOut()}}
function fadeOut(){if(ambient.paused)return;let v=ambient.volume;const x=setInterval(()=>{v-=.025;if(v<=0){clearInterval(x);ambient.pause();ambient.currentTime=0;ambient.volume=.16;document.getElementById('audioBtn').textContent='♪ Фон: выкл.'}else ambient.volume=v},80)}
if(!localStorage.getItem('consent_v'))current='consent';else{current='start';sid=uuid()}render();
